#!/usr/bin/env bash

set -Eeo pipefail

###########################
# Local Config Parameters #
###########################

AWS_DEFAULT_REGION=eu-west-2
IMAGE_REPO_NAME=repo/suspension-service

####################################
# Instance (Environment) Variables #
####################################

function configure_envs {
  export LOCALSTACK_URL="http://localhost:4566"
  export AWS_REGION="eu-west-2"
  export AWS_DEFAULT_REGION="eu-west-2"
  export S3_BUCKET_NAME="test-bucket"
  export DYNAMODB_NAME="local-test-db"
  export DYNAMODB_LOCAL_ENDPOINT="http://localhost:4566"
  export AWS_ACCESS_KEY_ID="LSIA5678901234567890"
  export AWS_SECRET_ACCESS_KEY="LSIA5678901234567890"
  export NHS_ENVIRONMENT="local"
}

function configure_sonar_environment_variable {
  export SONAR_TOKEN=$(_get_aws_ssm_secret "/repo/dev/output/suspensions-service/sonar_token")
}

#######################
# Terraform Functions #
#######################

function configure_local_envs {
  export LOCALSTACK_URL="http://localhost:4566"
  export AWS_REGION="eu-west-2"
  export AWS_DEFAULT_REGION="eu-west-2"
  export S3_BUCKET_NAME="test-bucket"
  export DYNAMODB_NAME="local-test-db"
  export DYNAMODB_LOCAL_ENDPOINT="http://localhost:4566"
  export AWS_ACCESS_KEY_ID="LSIA5678901234567890"
  export AWS_SECRET_ACCESS_KEY="LSIA5678901234567890"
  export NHS_ENVIRONMENT="local"
}

#############
# Functions #
#############

function start_localstack {
  echo "################################"
  echo "##### Starting Localstack ######"
  echo "################################"
  docker compose -f docker-compose.localstack-local.yaml up -d
}

function stop_localstack {
  echo "################################"
  echo "##### Stopping Localstack ######"
  echo "################################"
  docker compose -f docker-compose.localstack-local.yaml down
}

###########
## TASKS ##
###########

command="$1"
case "${command}" in
  start_localstack)
      start_localstack
      ;;
  stop_localstack)
      stop_localstack
      ;;
  build_docker)
      configure_envs
      ./tasks build
      configure_docker_repository_uri
      fetch_redaction_utils
      build_docker_image
      echo "Pushing the Docker image... $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG"
      docker push $REPOSITORY_URI:$IMAGE_TAG
      ;;
  build)
      rm -rf build/
      ./gradlew assemble
      ;;
  test_unit)
      ./gradlew test
      ;;
  test_integration)
      configure_envs
      start_localstack
      ./gradlew --info integration
      stop_localstack
      ;;
  test_coverage)
      configure_envs
      start_localstack
      ./gradlew jacocoTestCoverageVerification
      stop_localstack
      ;;
  code_quality)
      start_localstack
      ./gradlew check -x test -x integration
      stop_localstack
      ;;
  test_all)
      configure_envs
      start_localstack
      ./gradlew clean test integration jacocoTestCoverageVerification check
      stop_localstack
      ;;
  run_local)
      configure_envs
      ./gradlew bootRun
      ;;
  run_sonar)
      stop_localstack
      _assume_environment_role $NHS_ENVIRONMENT
      configure_envs
      configure_sonar_environment_variable
      ./gradlew build sonar --info
      ;;
  *)
      echo "Invalid command: '${command}'"
      exit 1
      ;;
esac
set +e
