#!/usr/bin/env bash

set -Eeo pipefail

###########################
# Local Config Parameters #
###########################

AWS_DEFAULT_REGION=eu-west-2
IMAGE_REPO_NAME=deductions/ehr-transfer-service
export NHS_SERVICE=ehr-transfer-service
AWS_HELPERS_VERSION=0.2.27
echo "AWS helper scripts version: $AWS_HELPERS_VERSION"

###########################
# Shared utils            #
###########################

function download_util() {
  local UTIL_VERSION=$1
  local UTIL_FILENAME=$2

  local UTIL_FILEPATH="utils/$UTIL_VERSION/$UTIL_FILENAME"

  mkdir -p "utils/$UTIL_VERSION"
  if [[ ! -f $UTIL_FILEPATH ]];then
    wget --quiet -O $UTIL_FILEPATH https://github.com/nhsconnect/prm-deductions-support-infra/releases/download/${UTIL_VERSION}/${UTIL_FILENAME}
  fi
  chmod +x $UTIL_FILEPATH

  echo "$UTIL_FILEPATH"
}

function fetch_redaction_utils() {
  download_util $AWS_HELPERS_VERSION run-with-redaction.sh
  download_util $AWS_HELPERS_VERSION redactor
}

# Do not change the file name as the aws helper scripts depend on it
AWS_HELPERS_FILE="utils/$AWS_HELPERS_VERSION/aws-helpers"

mkdir -p "utils/$AWS_HELPERS_VERSION"
if [[ ! -f $AWS_HELPERS_FILE ]];then
  wget --quiet -O $AWS_HELPERS_FILE https://github.com/nhsconnect/prm-deductions-support-infra/releases/download/${AWS_HELPERS_VERSION}/aws-helpers
fi
chmod +x $AWS_HELPERS_FILE
source $AWS_HELPERS_FILE

####################################
# Instance (Environment) Variables #
####################################

function check_env {
  if [[ -z "${NHS_ENVIRONMENT}" ]]; then
    echo "Must set NHS_ENVIRONMENT"
    exit 1
  fi
}

function set_image_tag() {
  if [[ -z "${GO_DEPENDENCY_LABEL_APP}" ]]; then
    export IMAGE_TAG=${GO_PIPELINE_LABEL:-$(git rev-parse HEAD | cut -c 1-8)}
  else
    export IMAGE_TAG=${GO_DEPENDENCY_LABEL_APP}
  fi
}

function configure_local_envs {
  export EHR_TRANSFER_SERVICE_MHS_QUEUE_URL_1="tcp://127.0.0.1:61616"
  export EHR_TRANSFER_SERVICE_MHS_QUEUE_URL_2="tcp://127.0.0.1:61617"
  export EHR_TRANSFER_SERVICE_TEST_ACTIVE_MQ_HOSTNAME="localhost"
  export EHR_TRANSFER_SERVICE_MHS_QUEUE_USERNAME="admin"
  export EHR_TRANSFER_SERVICE_MHS_QUEUE_PASSWORD="admin"
  export LOCALSTACK_URL="http://localhost:4566"
  export AWS_REGION="eu-west-2"
  export AWS_DEFAULT_REGION="eu-west-2"
  export S3_BUCKET_NAME="test-bucket"
  export DYNAMODB_NAME="local-test-db"
  export DYNAMODB_LOCAL_ENDPOINT="http://localhost:4566"
  export AWS_ACCESS_KEY_ID="LSIA5678901234567890"
  export AWS_SECRET_ACCESS_KEY="LSIA5678901234567890"
  export NHS_ENVIRONMENT="local"
}

function configure_sonar_environment_variable {
  export SONAR_TOKEN=$(_get_aws_ssm_secret "/repo/dev/output/ehr-transfer-service/sonar_token")
}

###########
## TASKS ##
###########

command="$1"
case "${command}" in
  assemble_docker)
      configure_local_envs
      ./tasks assemble
      configure_docker_repository_uri
      fetch_redaction_utils
      build_docker_image
      echo "Pushing the Docker image... $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG"
      docker push $REPOSITORY_URI:$IMAGE_TAG
      ;;
  show_image_tag)
      set_image_tag
      echo $IMAGE_TAG
      ;;
  build)
      rm -rf build/
      ./gradlew build -x integration
      ;;
  assemble)
      rm -rf build/
      ./gradlew assemble
      ;;
  test_unit)
      configure_local_envs
      ./gradlew test
      ;;
  test_integration)
#      ensure_prev_build_images_are_stopped
      configure_local_envs
      ./gradlew --info integration
      ;;
  test_coverage)
      ensure_prev_build_images_are_stopped
      configure_local_envs
      ./gradlew jacocoTestCoverageVerification
      ;;
  fetch_utils)
      fetch_redaction_utils
      ;;
  code_quality)
      ensure_prev_build_images_are_stopped
      configure_local_envs
      ./gradlew check -x test -x integration
      ;;
  test_all)
      configure_local_envs
      ./gradlew test integration jacocoTestCoverageVerification check
      ;;
  run_sonar)
      ensure_prev_build_images_are_stopped
      _assume_environment_role $NHS_ENVIRONMENT
      configure_local_envs
      configure_sonar_environment_variable
      ./gradlew build sonar --info
      ;;
  start_localstack)
      configure_local_envs
      docker compose -f docker-compose.localstack-local.yaml up -d
      ;;
  promote_docker_image)
      check_env
      set_image_tag
      promote_docker_image "$IMAGE_REPO_NAME:$IMAGE_TAG" "$NHS_ENVIRONMENT"
      ;;
  wait_ecs)
      check_env
      _assume_environment_role $NHS_ENVIRONMENT
      aws ecs wait services-stable \
        --region $AWS_DEFAULT_REGION \
        --cluster $NHS_ENVIRONMENT-${NHS_SERVICE}-ecs-cluster \
        --service $NHS_ENVIRONMENT-${NHS_SERVICE}
      ;;
  *)
      echo "Invalid command: '${command}'"
      exit 1
      ;;
esac
set +e
