#!/usr/bin/env bash

set -Eeo pipefail

###########################
# Local Config Parameters #
###########################

AWS_DEFAULT_REGION=eu-west-2
export NHS_SERVICE=re-registration-service
IMAGE_REPO_NAME=repo/$NHS_SERVICE

####################################
# Instance (Environment) Variables #
####################################

function check_env {
  if [[ -z "${NHS_ENVIRONMENT}" ]]; then
    echo "Must set NHS_ENVIRONMENT"
    exit 1
  fi
}

function get_aws_account_id {
    AWS_ACCOUNT_ID=$(aws sts get-caller-identity | jq -r .Account)
}

function configure_local_envs {
  export LOCALSTACK_URL="http://localhost:4566"
  export AWS_REGION="eu-west-2"
  export AWS_DEFAULT_REGION="eu-west-2"
  export S3_BUCKET_NAME="test-bucket"
  export DYNAMODB_NAME="local-test-db"
  export DYNAMODB_LOCAL_ENDPOINT="http://localhost:4566"
  export AWS_ACCESS_KEY_ID="LSIA5678901234567890"
  export AWS_SECRET_ACCESS_KEY="LSIA5678901234567890"
  export NHS_ENVIRONMENT="local"
}

function configure_sonar_environment_variable {
  export SONAR_TOKEN=$(_get_aws_ssm_secret "/repo/dev/output/re-registration-service/sonar_token")
}

#############
# FUNCTIONS #
#############
function start_localstack {
  echo "################################"
  echo "##### Starting Localstack ######"
  echo "################################"
  docker compose -f docker-compose.localstack-local.yaml up -d
}

function stop_localstack {
  echo "################################"
  echo "##### Stopping Localstack ######"
  echo "################################"
  docker compose -f docker-compose.localstack-local.yaml down
}

###########
## TASKS ##
###########

command="$1"
case "${command}" in
  start_localstack)
      configure_local_envs
      start_localstack
      ;;
  stop_localstack)
      stop_localstack
      ;;
  build)
      rm -rf build/
      ./gradlew assemble
      ;;
  test_unit)
      ./gradlew test
      ;;
  test_integration)
      configure_local_envs
      start_localstack
      ./gradlew --info integration
      stop_localstack
      ;;
  test_coverage)
      configure_local_envs
      start_localstack
      ./gradlew jacocoTestCoverageVerification
      stop_localstack
      ;;
  code_quality)
      start_localstack
      ./gradlew check -x test -x integration
      stop_localstack
      ;;
  test_all)
      configure_local_envs
      start_localstack
      ./gradlew test integration jacocoTestCoverageVerification check
      stop_localstack
      ;;
  run_sonar)
      configure_local_envs
      _assume_environment_role $NHS_ENVIRONMENT
      configure_sonar_environment_variable
      start_localstack
      ./gradlew build sonar --info
      stop_localstack
      ;;
  run_local)
      configure_local_envs
      ./gradlew bootRun
      ;;
esac
set +e
