#!/usr/bin/env bash

set -Eeo pipefail

###########################
# Local Config Parameters #
###########################

AWS_DEFAULT_REGION=eu-west-2

# used for docker push and promotion, but beware ecs tasks managed by terraform var.component+name
IMAGE_REPO_NAME=deductions/ehr-out-service

# used to identify ssm param names
GIT_REPO_NAME=prm-repo-ehr-out-service

# NB change of this will change state file name (need to use -migrate-state on inits) as well as expected ecs-cluster names in this file
export OLD_SERVICE=repo-to-gp
export NHS_SERVICE=ehr-out-service


####################################
# Instance (Environment) Variables #
####################################

function check_env {
  if [[ -z "${NHS_ENVIRONMENT}" ]]; then
    echo "Must set NHS_ENVIRONMENT"
    exit 1
  fi
}

function configure_service_url {
  if [[ -z "${NHS_ENVIRONMENT}" ]]; then
    export SERVICE_URL=http://${NHS_SERVICE}:3000
  else
    export SERVICE_URL="https://${NHS_SERVICE}.${NHS_ENVIRONMENT}.non-prod.patient-deductions.nhs.uk"
  fi
}

function set_image_tag() {
  if [[ -z "${GO_DEPENDENCY_LABEL_APP}" ]]; then
    export IMAGE_TAG=${GO_PIPELINE_LABEL:-$(git rev-parse HEAD | cut -c 1-8)}
  else
    export IMAGE_TAG=${GO_DEPENDENCY_LABEL_APP}
  fi
}

function prepare_local_envs_for_ide {
  envs=$( printenv | grep "REPOSITORY_URI" && \
          printenv | grep "SERVICE_URL"
  )
  echo "Paste these env vars to your Intelij run template:"
  echo $envs | tr ' ' ';'
}

function generate_secure_string {
  local length=$1
  LC_CTYPE="en_GB.UTF8" tr -dc 'A-Za-z0-9' < /dev/urandom | head -c $length ; echo
}

function configure_local_envs {
  export GP2GP_MESSENGER_AUTHORIZATION_KEYS="auth-key-1"
  export EHR_REPO_AUTHORIZATION_KEYS="auth-key-2"
  export GP2GP_MESSENGER_SERVICE_URL="http://localhost:3001"
  export EHR_REPO_SERVICE_URL="http://localhost:3002"
  export LOCALSTACK_URL="http://localstack:4566"
  export REPOSITORY_URI="deductions/ehr-out-service"
  export DYNAMODB_NAME="local-test-db"
  export DYNAMODB_LOCAL_ENDPOINT="http://localhost:4573/"
  export AWS_ACCESS_KEY_ID="LSIA5678901234567890"
  export AWS_SECRET_ACCESS_KEY="LSIA5678901234567890"
  export NHS_ENVIRONMENT="local"
  export AWS_REGION="eu-west-2"
  export AWS_DEFAULT_REGION="eu-west-2"
  configure_service_url
  set_image_tag
}

function configure_local_envs_for_docker_test {
  export GP2GP_MESSENGER_AUTHORIZATION_KEYS=auth-key-1
  export EHR_REPO_AUTHORIZATION_KEYS=auth-key-2
  export GP2GP_MESSENGER_SERVICE_URL="www.notreal.com"
  export EHR_REPO_SERVICE_URL="www.alsonotreal.com"
  export LOCALSTACK_URL="http://localstack:4566"
  export AWS_REGION=${AWS_DEFAULT_REGION}
  export REPOSITORY_URI="deductions/ehr-out-service"

  export DYNAMODB_NAME=local-test-db
  export DYNAMODB_LOCAL_ENDPOINT=http://dynamodb-local:8000/

  configure_service_url
  set_image_tag
}

############################
# Docker Related Functions #
############################


function configure_docker_repository_uri {
  docker_login
  get_aws_account_id
  export REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/$IMAGE_REPO_NAME
}

function kill_container {
  local filter=$1
  local moniker=$2

  echo docker processes running: $(docker ps)

  DOCKER_CONTAINERS_MATCHING_FILTER=$(docker ps --filter $filter -q)

  echo docker processes looking like $2 running matching filter: $DOCKER_CONTAINERS_MATCHING_FILTER

  if [ -z "$DOCKER_CONTAINERS_MATCHING_FILTER" ]; then
    echo no $moniker nonsense going on, cool
  else
    echo trying to kill $moniker...
    docker stop $DOCKER_CONTAINERS_MATCHING_FILTER
  fi
}

function destroy_localstack {
  kill_container publish=4566 localstack
  kill_container publish=4573 dynamodb-local
}
function start_localstack {
  docker-compose -f docker-compose.localstack-local.yaml up -d
}
function start_localstack_itest {
  docker-compose -f docker-compose-itest.yml up -d
}

###########
# Testing #
###########

function test_functional {
  check_env
  npm install
  if [[ $NHS_ENVIRONMENT == "dev" ]]; then
    npm run test:health
  else
    npm run test:functional
  fi
}

###########
## TASKS ##
###########

command="$1"
case "${command}" in
  dep)
      npm install
      npm run check-audit
      ;;
  fix_dep)
      npm install
      npm run resolve-audit
      ;;
  start_localstack_itest)
      start_localstack_itest
      ;;
  list_outdated)
      npm install
      npm outdated > outdated-dependencies.txt
      ;;
  destroy_localstack)
      destroy_localstack
      ;;
  test_lint)
      npm install
      npm run lint || true # retain lint for WIP tracking and advisory but don't break build
      ;;
  test_unit)
      npm install
      npm run test:unit
      ;;
  setup_test_integration_local)
      configure_local_envs
      sh scripts/create-dynamodb-table.sh
      prepare_local_envs_for_ide
      ;;
  test_integration)
      configure_local_envs
      start_localstack
      npm install
      sh scripts/create-dynamodb-table.sh
      npm run test:integration
      destroy_localstack
      ;;
  start_localstack)
      start_localstack
      ;;
  test_functional)
      configure_service_url
      test_functional
      ;;
  test_coverage)
      configure_local_envs
      start_localstack
      npm install
      sh scripts/create-dynamodb-table.sh
      npm run test:coverage
      destroy_localstack
      ;;
  test_coverage_github_action)
      npm install
      npm run test:coverage-unit-test-only
      ;;
  build)
      rm -rf build
      npm install
      npm run build
      ;;
  build_docker_local)
      configure_local_envs_for_docker_test
      build_docker_image
      ;;
  build_docker)
      configure_docker_repository_uri
      build_docker_image
      echo "Pushing the Docker image... $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG"
      docker push $REPOSITORY_URI:$IMAGE_TAG
      ;;
  test_docker)
      configure_local_envs_for_docker_test
      configure_docker_repository_uri
      npm install
      sh scripts/create-dynamodb-table.sh
      npm run test:docker
      ;;
  run_docker_local)
      configure_local_envs
      run_docker_local
      ;;
  tf_plan)
      check_env
      _assume_environment_role $NHS_ENVIRONMENT
      tf_plan "$2"
      ;;
  tf_apply)
      check_env
      _assume_environment_role $NHS_ENVIRONMENT
      tf_apply
      ;;
  create_secrets)
      check_env
      _assume_environment_role $NHS_ENVIRONMENT
      ;;
  promote_docker_image)
      check_env
      set_image_tag
      promote_docker_image "$IMAGE_REPO_NAME:$IMAGE_TAG" "$NHS_ENVIRONMENT"
      ;;
  wait_ecs)
      check_env
      _assume_environment_role $NHS_ENVIRONMENT
      aws ecs wait services-stable \
        --region $AWS_DEFAULT_REGION \
        --cluster $NHS_ENVIRONMENT-${NHS_SERVICE} \
        --service $NHS_ENVIRONMENT-${NHS_SERVICE}
      ;;
  *)
      echo "Invalid command: '${command}'"
      exit 1
      ;;
esac
set +e