name: Full Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Which environment would you like to deploy to?"
        type: choice
        options:
          - dev
          - pre-prod
          - prod
        required: true
      is_deployment:
        description: "Do you want to apply changes?"
        type: boolean
        default: false
        required: true
  workflow_call:
    inputs:
      environment:
        default: dev
        type: string
      is_deployment:
        description: "Do you want to apply changes?"
        type: boolean
        default: true

permissions:
  pull-requests: write
  id-token: write
  contents: read

jobs:
  ehr-repo:
    name: EHR Repo CI
    secrets: inherit
    uses: "./.github/workflows/base-node-service-jobs.yml"
    with:
      service: ehr-repo
      environment: ${{ inputs.environment }}
      is_deployment: ${{ inputs.is_deployment }}
      ecr_alias: deductions/ehr-repo

  ehr-out-service:
    name: EHR Out Service CI
    secrets: inherit
    uses: "./.github/workflows/base-node-service-jobs.yml"
    with:
      service: ehr-out-service
      environment: ${{ inputs.environment }}
      is_deployment: ${{ inputs.is_deployment }}
      ecr_alias: deductions/ehr-out-service

  mesh-forwarder:
    name: MESH Forwarder CI
    uses: "./.github/workflows/base-python-service-jobs.yml"
    with:
      service: mesh-forwarder
      environment: ${{ inputs.environment }}
      is_deployment: ${{ inputs.is_deployment }}
      ecr_alias: deductions/mesh-forwarder
    secrets: inherit

  gp2gp-messenger:
    name: GP2GP Messenger CI
    uses: "./.github/workflows/base-node-service-jobs.yml"
    with:
      service: gp2gp-messenger
      environment: ${{ inputs.environment }}
      is_deployment: ${{ inputs.is_deployment }}
      ecr_alias: deductions/gp2gp-messenger
    secrets: inherit

  nems-event-processor:
    name: NEMs Event Processor CI
    uses: "./.github/workflows/base-java-service-jobs.yml"
    with:
      service: nems-event-processor
      environment: ${{ inputs.environment }}
      is_deployment: ${{ inputs.is_deployment }}
      requires_localstack: true
      ecr_alias: deductions/nems-event-processor
    secrets: inherit

  ehr-transfer-service:
    name: EHR Transfer Service CI
    uses: "./.github/workflows/base-java-service-jobs.yml"
    with:
      service: ehr-transfer-service
      environment: ${{ inputs.environment }}
      is_deployment: ${{ inputs.is_deployment }}
      requires_localstack: true
      ecr_alias: deductions/ehr-transfer-service
    secrets: inherit

  pds-adaptor:
    name: PDS Adaptor CI
    uses: "./.github/workflows/base-java-service-jobs.yml"
    with:
      service: pds-adaptor
      environment: ${{ inputs.environment }}
      is_deployment: ${{ inputs.is_deployment }}
      ecr_alias: deductions/pds-adaptor
    secrets: inherit

  re-registration-service:
    name: Re-registration Service CI
    uses: "./.github/workflows/base-java-service-jobs.yml"
    with:
      service: re-registration-service
      environment: ${{ inputs.environment }}
      is_deployment: ${{ inputs.is_deployment }}
      requires_localstack: true
      image_prefix: repo/
      ecr_alias: repo/re-registration-service
    secrets: inherit

  suspension-service:
    name: Suspension Service CI
    uses: "./.github/workflows/base-java-service-jobs.yml"
    with:
      service: suspension-service
      environment: ${{ inputs.environment }}
      is_deployment: ${{ inputs.is_deployment }}
      requires_localstack: true
      image_prefix: repo/
      ecr_alias: repo/suspension-service
    secrets: inherit

  e2e-testing:
    name: End to End
    if: ${{ vars.E2E_TESTS_ENABLED == 'true' && success() }}
    needs: [ehr-repo, ehr-out-service, mesh-forwarder]
    uses: ./.github/workflows/e2e.yml
    secrets: inherit
